### ISSUE TITLE
SELECT WHERE ID in with duplicated IDs

### ISSUE THREAD

**Issue by tatchi** [tim-smart/sqlfx#174]
Given the following SQLite table:

```sql
CREATE TABLE "users" ("id" integer NOT NULL,"name" varchar NOT NULL, PRIMARY KEY (id));
```

With two users:
<table>
    <tr>
        <th>id</th>
        <th>name</th>
    </tr>
    <tr>
        <td>1</td>
        <td>user 1</td>
    </tr>
    <tr>
        <td>2</td>
        <td>user 2</td>
    </tr>
</table>

If we manually run the following query:

```sqlite
SELECT * FROM users where id in (1,2,1)
```

It returns two rows. If we do the same with sqlfx:

```ts
const GetById = sql.resolverId('GetUserById', {
  id: S.number,
  result: UserDbo,
  resultId: (_) => _.id,
  run: (ids) => sql`SELECT * FROM users WHERE id IN ${sql(ids)}`,
});

const getUserById = (id: number) =>
  Effect.gen(function* (_) {
    const user = yield* _(
      GetById.execute(id).pipe(Effect.map(Option.map((p) => new UserDbo(p))))
    );

    return user;
  });

const main = Effect.gen(function* (_) {
const { getUserById } = yield* _(UserRepro);

const allUsers = yield* _(
  Effect.all(
    pipe(
      [1, 2, 1],
      ReadonlyArray.map((id) => getUserById(id))
    ),
    { batching: false }
  )
);

console.log(allUsers);

return null;
});		
```

It returns 3 rows:

```ts
[
  {
    _id: 'Option',
    _tag: 'Some',
    value: UserDbo { id: 1, name: 'user 1' }
  },
  {
    _id: 'Option',
    _tag: 'Some',
    value: UserDbo { id: 2, name: 'user 2' }
  },
  {
    _id: 'Option',
    _tag: 'Some',
    value: UserDbo { id: 1, name: 'user 1' }
  }
]
```

If we set `batching` to `true`, it gives the following error

```
Exited failure state: All fibers interrupted without errors.
```

Is it expected? Shouldn't the code return 2 rows in both cases?

### Repro

* clone https://github.com/tatchi/sqlx-repro
* git checkout same-id
* pnpm i
* ./src/main.ts

**Comment by tatchi** [comment]
Thanks 🤗 Just to be sure, it doesn't fail anymore but returns 3 rows (with duplicate user 1) both with batching on or off. Is this the expected result?

**Comment by tim-smart** [comment]
Yes, with a resolver this is the correct behaviour :)
